/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MB' at '9/19/16 8:58 AM' with Gradle 2.14.1
 *
 * @author MB, @date 9/19/16 8:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
